name: Continuous Commits and PRs

on:
  workflow_dispatch:
    inputs:
      commit_count:
        description: "Jumlah commit yang ingin dibuat"
        default: "1500"
      year:
        description: "Tahun target (opsional)"
        default: "2025"

jobs:
  generate-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git identity
        run: |
          git config --global user.name "ThoriqRohan"
          git config --global user.email "thoriq@example.com"

      - name: Create new branch
        run: |
          BRANCH_NAME="update-$(date +%s)"
          git checkout -b $BRANCH_NAME
          echo "Branch baru: $BRANCH_NAME" >> branch.log
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Generate commits
        run: |
          for ((i=1; i<=${{ github.event.inputs.commit_count }}; i++)); do
            echo "Generated commit $i for ${{ github.event.inputs.year }}" >> commits.txt
            git add commits.txt
            git commit -m "Commit ke-$i untuk ${{ github.event.inputs.year }}"
          done

      - name: Push branch
        run: |
          git push https://${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          gh pr create \
            --title "Generated PR ${{ github.event.inputs.year }}" \
            --body "Automated PR dengan ${{ github.event.inputs.commit_count }} commit untuk ${{ github.event.inputs.year }}" \
            --base main \
            --head ${{ env.BRANCH_NAME }} || echo "PR sudah ada atau gagal dibuat"
