name: Continuous Commits and PRs

on:
  workflow_dispatch:

jobs:
  generate-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git identity
        run: |
          git config --global user.name "ThoriqRohan"
          git config --global user.email "thoriq@example.com"

      - name: Generate commits
        run: |
          for i in {1..10}; do
            echo "Commit number $i" >> commits.log
            git add commits.log
            git commit -m "Generated commit $i"
          done
          git push https://${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          gh pr create --title "Auto PR $(date)" --body "Generated automatically via workflow" --base main --head main || echo "PR already exists"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
