name: Massive Commits and PRs

on:
  workflow_dispatch:
    inputs:
      total_batches:
        description: "Jumlah batch (misal 15)"
        default: "127"
      commits_per_batch:
        description: "Jumlah commit per batch (misal 100)"
        default: "13"
      year:
        description: "Tahun target"
        default: "2025"

jobs:
  commit-pr-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name "ThoriqRohan"
          git config --global user.email "thoriq@example.com"

      - name: Generate commits and PRs
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          for ((batch=1; batch<=${{ github.event.inputs.total_batches }}; batch++)); do
            BRANCH_NAME="update-$(date +%s)-$RANDOM"
            git checkout -b $BRANCH_NAME

            for ((i=1; i<=${{ github.event.inputs.commits_per_batch }}; i++)); do
              echo "$(date) | Commit ke-$i dari batch-$batch untuk ${{ github.event.inputs.year }}" >> commits.log
              git add commits.log
              git commit -m "Commit $i (batch-$batch, ${{ github.event.inputs.year }})"
            done

            git push https://${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$BRANCH_NAME

            gh pr create \
              --title "Batch-$batch: ${{ github.event.inputs.commits_per_batch }} commits" \
              --body "Batch $batch dengan ${{ github.event.inputs.commits_per_batch }} commits untuk ${{ github.event.inputs.year }}" \
              --base main \
              --head $BRANCH_NAME || echo "PR sudah ada"
          done
